# Generated by Django 3.0.4 on 2020-08-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
    ]
