# Generated by Django 3.0.4 on 2020-08-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200823_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='also_read',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='also_read_link',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
