# Generated by Django 3.0.4 on 2020-09-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200821_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_bio', models.CharField(max_length=10000)),
                ('author_interests', models.CharField(max_length=1000)),
                ('author_image_link', models.CharField(max_length=10000000000)),
            ],
        ),
    ]
