# Generated by Django 3.0.4 on 2020-09-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_bio',
            new_name='authorbio',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_image_link',
            new_name='authorimagelink',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_interests',
            new_name='authorinterest1',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='authorname',
        ),
        migrations.AddField(
            model_name='author',
            name='authorinterest2',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='authorinterest3',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
